// src/react/TailwindScreenSize.tsx
"use client";
import React, { useEffect, useState, useMemo } from "react";
import { twMerge } from "tailwind-merge";
import type {
  Position,
  Theme,
  TailwindScreenSizeProps,
  Breakpoint,
} from "./types";
import { detectTailwind } from "./utils";

const positionClasses: Record<Position, string> = {
  "top-left": "top-5 left-5",
  "top-right": "top-5 right-5",
  "bottom-left": "bottom-5 left-5",
  "bottom-right": "bottom-5 right-5",
  "top-center": "top-5 left-1/2 -translate-x-1/2",
  "bottom-center": "bottom-5 left-1/2 -translate-x-1/2",
};

const themeClasses: Record<
  Theme,
  {
    container: string;
    text: string;
    divider: string;
    breakpoint: string;
  }
> = {
  dark: {
    container: "bg-gray-900/90 text-white",
    text: "text-white",
    divider: "bg-gray-700",
    breakpoint: "text-gray-400",
  },
  light: {
    container: "bg-white/90 text-gray-900",
    text: "text-gray-900",
    divider: "bg-gray-200",
    breakpoint: "text-gray-600",
  },
  glass: {
    container: "bg-white/10 backdrop-blur-md border border-white/20 shadow-lg",
    text: "text-white",
    divider: "bg-white/20",
    breakpoint: "text-white/80",
  },
  minimal: {
    container: "bg-transparent",
    text: "text-gray-600 dark:text-gray-300",
    divider: "bg-gray-300 dark:bg-gray-700",
    breakpoint: "text-gray-500 dark:text-gray-400",
  },
  slate: {
    container: "bg-slate-600/90 text-white",
    text: "text-white",
    divider: "bg-slate-400",
    breakpoint: "text-slate-200",
  },
  gray: {
    container: "bg-gray-600/90 text-white",
    text: "text-white",
    divider: "bg-gray-400",
    breakpoint: "text-gray-200",
  },
  zinc: {
    container: "bg-zinc-600/90 text-white",
    text: "text-white",
    divider: "bg-zinc-400",
    breakpoint: "text-zinc-200",
  },
  neutral: {
    container: "bg-neutral-600/90 text-white",
    text: "text-white",
    divider: "bg-neutral-400",
    breakpoint: "text-neutral-200",
  },
  stone: {
    container: "bg-stone-600/90 text-white",
    text: "text-white",
    divider: "bg-stone-400",
    breakpoint: "text-stone-200",
  },
  red: {
    container: "bg-red-600/90 text-white",
    text: "text-white",
    divider: "bg-red-400",
    breakpoint: "text-red-200",
  },
  orange: {
    container: "bg-orange-600/90 text-white",
    text: "text-white",
    divider: "bg-orange-400",
    breakpoint: "text-orange-200",
  },
  amber: {
    container: "bg-amber-600/90 text-white",
    text: "text-white",
    divider: "bg-amber-400",
    breakpoint: "text-amber-200",
  },
  yellow: {
    container: "bg-yellow-500/90 text-white",
    text: "text-white",
    divider: "bg-yellow-300",
    breakpoint: "text-yellow-100",
  },
  lime: {
    container: "bg-lime-600/90 text-white",
    text: "text-white",
    divider: "bg-lime-400",
    breakpoint: "text-lime-200",
  },
  green: {
    container: "bg-green-600/90 text-white",
    text: "text-white",
    divider: "bg-green-400",
    breakpoint: "text-green-200",
  },
  emerald: {
    container: "bg-emerald-600/90 text-white",
    text: "text-white",
    divider: "bg-emerald-400",
    breakpoint: "text-emerald-200",
  },
  teal: {
    container: "bg-teal-600/90 text-white",
    text: "text-white",
    divider: "bg-teal-400",
    breakpoint: "text-teal-200",
  },
  cyan: {
    container: "bg-cyan-600/90 text-white",
    text: "text-white",
    divider: "bg-cyan-400",
    breakpoint: "text-cyan-200",
  },
  sky: {
    container: "bg-sky-600/90 text-white",
    text: "text-white",
    divider: "bg-sky-400",
    breakpoint: "text-sky-200",
  },
  blue: {
    container: "bg-blue-600/90 text-white",
    text: "text-white",
    divider: "bg-blue-400",
    breakpoint: "text-blue-200",
  },
  indigo: {
    container: "bg-indigo-600/90 text-white",
    text: "text-white",
    divider: "bg-indigo-400",
    breakpoint: "text-indigo-200",
  },
  violet: {
    container: "bg-violet-600/90 text-white",
    text: "text-white",
    divider: "bg-violet-400",
    breakpoint: "text-violet-200",
  },
  purple: {
    container: "bg-purple-600/90 text-white",
    text: "text-white",
    divider: "bg-purple-400",
    breakpoint: "text-purple-200",
  },
  fuchsia: {
    container: "bg-fuchsia-600/90 text-white",
    text: "text-white",
    divider: "bg-fuchsia-400",
    breakpoint: "text-fuchsia-200",
  },
  pink: {
    container: "bg-pink-600/90 text-white",
    text: "text-white",
    divider: "bg-pink-400",
    breakpoint: "text-pink-200",
  },
  rose: {
    container: "bg-rose-600/90 text-white",
    text: "text-white",
    divider: "bg-rose-400",
    breakpoint: "text-rose-200",
  },
};

const defaultBreakpoints: Breakpoint[] = [
  { screenTitle: "XS", minWidth: 0 },
  { screenTitle: "SM", minWidth: 640 },
  { screenTitle: "MD", minWidth: 768 },
  { screenTitle: "LG", minWidth: 1024 },
  { screenTitle: "XL", minWidth: 1280 },
  { screenTitle: "2XL", minWidth: 1536 },
];

const isDevelopment = () => {
  return process.env.NODE_ENV === "development";
};

const baseClasses = {
  container:
    "fixed flex items-center gap-2 rounded-full px-2.5 py-1 font-mono text-xs font-medium transition-all duration-200",
  divider: "h-4 w-px",
};

export const TailwindScreenSize: React.FC<TailwindScreenSizeProps> = ({
  className = "",
  position = "bottom-right",
  theme = "dark",
  show,
  containerClassName = "",
  textClassName = "",
  dividerClassName = "",
  breakpointClassName = "",
  breakpoints,
  showDefaultBreakpoints = true,
  hideNoTailwindCSSWarning = false,
}) => {
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 });
  const [mounted, setMounted] = useState(false);
  const [currentBreakpoint, setCurrentBreakpoint] = useState<string>("");
  const [hasTailwind, setHasTailwind] = useState(true);

  const allBreakpoints = useMemo(() => {
    const customBreakpoints = breakpoints || [];
    if (!showDefaultBreakpoints) return customBreakpoints;
    return [...defaultBreakpoints, ...customBreakpoints].sort(
      (a, b) => a.minWidth - b.minWidth
    );
  }, [breakpoints, showDefaultBreakpoints]);

  useEffect(() => {
    setMounted(true);
    const tailwindDetected = detectTailwind();
    setHasTailwind(tailwindDetected);

    function updateDimensions() {
      const width = window.innerWidth;
      const height = window.innerHeight;
      setDimensions({ width, height });

      // Find the current breakpoint
      const current =
        allBreakpoints
          .slice()
          .reverse()
          .find((bp) => width >= bp.minWidth)?.screenTitle || "";
      setCurrentBreakpoint(current);
    }

    updateDimensions();
    window.addEventListener("resize", updateDimensions);

    return () => {
      window.removeEventListener("resize", updateDimensions);
    };
  }, [allBreakpoints]);

  // Don't render anything on the server
  if (!mounted) return null;

  // Don't render if show is explicitly set to false, regardless of environment
  if (show === false) return null;

  // Don't render if not in development unless show is explicitly set to true
  if (!isDevelopment() && show !== true) return null;

  const { width, height } = dimensions;
  const themeStyles = themeClasses[theme];

  return (
    <div
      className={twMerge(
        baseClasses.container,
        positionClasses[position],
        themeStyles.container,
        containerClassName,
        className
      )}
    >
      <span className={twMerge(themeStyles.text, textClassName)}>
        {width.toLocaleString()} × {height.toLocaleString()}
      </span>
      <div
        className={twMerge(
          baseClasses.divider,
          themeStyles.divider,
          dividerClassName
        )}
      />
      <span className={twMerge(themeStyles.breakpoint, breakpointClassName)}>
        {currentBreakpoint}
      </span>
      {!hasTailwind && !hideNoTailwindCSSWarning && (
        <>
          <div
            className={twMerge(
              baseClasses.divider,
              themeStyles.divider,
              dividerClassName
            )}
          />
          <span
            className={twMerge(themeStyles.breakpoint, breakpointClassName)}
          >
            No TailwindCSS Detected
          </span>
        </>
      )}
    </div>
  );
};

// src/svelte/TailwindScreenSize.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { twMerge } from 'tailwind-merge';
	import type { Position, Theme, Breakpoint, TailwindScreenSizeProps } from '../types';
	import { detectTailwind } from '../utils';

	// Props
	const {
		className = '',
		position = /** @type {Position} */ ('bottom-right'),
		theme = /** @type {Theme} */ ('dark'),
		show = /** @type {boolean | undefined} */ (undefined),
		containerClassName = '',
		textClassName = '',
		dividerClassName = '',
		breakpointClassName = '',
		breakpoints = /** @type {Breakpoint[] | undefined} */ (undefined),
		showDefaultBreakpoints = true,
		hideNoTailwindCSSWarning = false
	}: TailwindScreenSizeProps = $props();

	// State
	let currentBreakpoint = $state('');
	let width = $state(0);
	let isTailwindDetected = $state(false);
	let mounted = $state(false);

	const positionClasses: Record<Position, string> = {
		'top-left': 'top-5 left-5',
		'top-right': 'top-5 right-5',
		'bottom-left': 'bottom-5 left-5',
		'bottom-right': 'bottom-5 right-5',
		'top-center': 'top-5 left-1/2 -translate-x-1/2',
		'bottom-center': 'bottom-5 left-1/2 -translate-x-1/2'
	};

	const themeClasses: Record<
		Theme,
		{ container: string; text: string; divider: string; breakpoint: string }
	> = {
		dark: {
			container: 'bg-gray-900/90 text-white',
			text: 'text-white',
			divider: 'bg-gray-700',
			breakpoint: 'text-gray-400'
		},
		light: {
			container: 'bg-white/90 text-gray-900',
			text: 'text-gray-900',
			divider: 'bg-gray-200',
			breakpoint: 'text-gray-600'
		},
		glass: {
			container: 'bg-white/30 backdrop-blur-lg text-gray-900',
			text: 'text-gray-900',
			divider: 'bg-gray-300/50',
			breakpoint: 'text-gray-600'
		},
		minimal: {
			container: 'bg-white/10 text-gray-800',
			text: 'text-gray-800',
			divider: 'bg-gray-300',
			breakpoint: 'text-gray-500'
		},
		slate: {
			container: 'bg-slate-100/90 text-slate-900',
			text: 'text-slate-900',
			divider: 'bg-slate-300',
			breakpoint: 'text-slate-600'
		},
		gray: {
			container: 'bg-gray-100/90 text-gray-900',
			text: 'text-gray-900',
			divider: 'bg-gray-300',
			breakpoint: 'text-gray-600'
		},
		zinc: {
			container: 'bg-zinc-100/90 text-zinc-900',
			text: 'text-zinc-900',
			divider: 'bg-zinc-300',
			breakpoint: 'text-zinc-600'
		},
		neutral: {
			container: 'bg-neutral-100/90 text-neutral-900',
			text: 'text-neutral-900',
			divider: 'bg-neutral-300',
			breakpoint: 'text-neutral-600'
		},
		stone: {
			container: 'bg-stone-100/90 text-stone-900',
			text: 'text-stone-900',
			divider: 'bg-stone-300',
			breakpoint: 'text-stone-600'
		},
		red: {
			container: 'bg-red-100/90 text-red-900',
			text: 'text-red-900',
			divider: 'bg-red-300',
			breakpoint: 'text-red-600'
		},
		orange: {
			container: 'bg-orange-100/90 text-orange-900',
			text: 'text-orange-900',
			divider: 'bg-orange-300',
			breakpoint: 'text-orange-600'
		},
		amber: {
			container: 'bg-amber-100/90 text-amber-900',
			text: 'text-amber-900',
			divider: 'bg-amber-300',
			breakpoint: 'text-amber-600'
		},
		yellow: {
			container: 'bg-yellow-100/90 text-yellow-900',
			text: 'text-yellow-900',
			divider: 'bg-yellow-300',
			breakpoint: 'text-yellow-600'
		},
		lime: {
			container: 'bg-lime-100/90 text-lime-900',
			text: 'text-lime-900',
			divider: 'bg-lime-300',
			breakpoint: 'text-lime-600'
		},
		green: {
			container: 'bg-green-100/90 text-green-900',
			text: 'text-green-900',
			divider: 'bg-green-300',
			breakpoint: 'text-green-600'
		},
		emerald: {
			container: 'bg-emerald-100/90 text-emerald-900',
			text: 'text-emerald-900',
			divider: 'bg-emerald-300',
			breakpoint: 'text-emerald-600'
		},
		teal: {
			container: 'bg-teal-100/90 text-teal-900',
			text: 'text-teal-900',
			divider: 'bg-teal-300',
			breakpoint: 'text-teal-600'
		},
		cyan: {
			container: 'bg-cyan-100/90 text-cyan-900',
			text: 'text-cyan-900',
			divider: 'bg-cyan-300',
			breakpoint: 'text-cyan-600'
		},
		sky: {
			container: 'bg-sky-100/90 text-sky-900',
			text: 'text-sky-900',
			divider: 'bg-sky-300',
			breakpoint: 'text-sky-600'
		},
		blue: {
			container: 'bg-blue-100/90 text-blue-900',
			text: 'text-blue-900',
			divider: 'bg-blue-300',
			breakpoint: 'text-blue-600'
		},
		indigo: {
			container: 'bg-indigo-100/90 text-indigo-900',
			text: 'text-indigo-900',
			divider: 'bg-indigo-300',
			breakpoint: 'text-indigo-600'
		},
		violet: {
			container: 'bg-violet-100/90 text-violet-900',
			text: 'text-violet-900',
			divider: 'bg-violet-300',
			breakpoint: 'text-violet-600'
		},
		purple: {
			container: 'bg-purple-100/90 text-purple-900',
			text: 'text-purple-900',
			divider: 'bg-purple-300',
			breakpoint: 'text-purple-600'
		},
		fuchsia: {
			container: 'bg-fuchsia-100/90 text-fuchsia-900',
			text: 'text-fuchsia-900',
			divider: 'bg-fuchsia-300',
			breakpoint: 'text-fuchsia-600'
		},
		pink: {
			container: 'bg-pink-100/90 text-pink-900',
			text: 'text-pink-900',
			divider: 'bg-pink-300',
			breakpoint: 'text-pink-600'
		},
		rose: {
			container: 'bg-rose-100/90 text-rose-900',
			text: 'text-rose-900',
			divider: 'bg-rose-300',
			breakpoint: 'text-rose-600'
		}
	};

	const defaultBreakpoints: Breakpoint[] = [
		{ screenTitle: 'XS', minWidth: 0 },
		{ screenTitle: 'SM', minWidth: 640 },
		{ screenTitle: 'MD', minWidth: 768 },
		{ screenTitle: 'LG', minWidth: 1024 },
		{ screenTitle: 'XL', minWidth: 1280 },
		{ screenTitle: '2XL', minWidth: 1536 }
	];

	const baseClasses = {
		container:
			'fixed flex items-center gap-2 rounded-full px-2.5 py-1 font-mono text-xs font-medium transition-all duration-200',
		divider: 'h-4 w-px'
	};

	function isDevelopment() {
		return process.env.NODE_ENV === 'development';
	}

	function getCurrentBreakpoint(width: number, breakpointList: Breakpoint[]) {
		const sortedBreakpoints = [...breakpointList].sort((a, b) => b.minWidth - a.minWidth);
		return sortedBreakpoints.find((breakpoint) => width >= breakpoint.minWidth)?.screenTitle || '';
	}

	function handleResize() {
		width = window.innerWidth;
		currentBreakpoint = getCurrentBreakpoint(width, breakpoints || defaultBreakpoints);
	}

	// Derived values
	// $: shouldShow = show ?? isDevelopment();
	const shouldShow = $derived(show ?? isDevelopment());
	// $: activeBreakpoints = breakpoints || (showDefaultBreakpoints ? defaultBreakpoints : []);
	const activeBreakpoints = $derived(
		breakpoints || (showDefaultBreakpoints ? defaultBreakpoints : [])
	);
	// $: containerClassNames = twMerge(
	// 	baseClasses.container,
	// 	themeClasses[theme].container,
	// 	positionClasses[position],
	// 	containerClassName,
	// 	className
	// );
	const containerClassNames = $derived(
		twMerge(
			baseClasses.container,
			themeClasses[theme].container,
			positionClasses[position],
			containerClassName,
			className
		)
	);
	// $: textClassNames = twMerge(themeClasses[theme].text, textClassName);
	const textClassNames = $derived(twMerge(themeClasses[theme].text, textClassName));
	// $: dividerClassNames = twMerge(
	// 	baseClasses.divider,
	// 	themeClasses[theme].divider,
	// 	dividerClassName
	// );
	const dividerClassNames = $derived(
		twMerge(baseClasses.divider, themeClasses[theme].divider, dividerClassName)
	);
	// $: breakpointClassNames = twMerge(
	// 	themeClasses[theme].breakpoint,
	// 	breakpointClassName
	// );
	const breakpointClassNames = $derived(
		twMerge(themeClasses[theme].breakpoint, breakpointClassName)
	);
	// $: breakpointClassNames = twMerge(themeClasses[theme].breakpoint, breakpointClassName);

	// Lifecycle
	onMount(() => {
		mounted = true;
		isTailwindDetected = detectTailwind();
		handleResize();
		window.addEventListener('resize', handleResize);
		return () => {
			window.removeEventListener('resize', handleResize);
		};
	});
</script>

{#if mounted && shouldShow}
	{#if !isTailwindDetected && !hideNoTailwindCSSWarning}
		<div class="fixed bottom-5 left-5 text-xs text-red-500">Tailwind CSS not detected</div>
	{/if}
	<div class={containerClassNames}>
		<span class={textClassNames}>{width}px</span>
		<div class={dividerClassNames}></div>
		<span class={breakpointClassNames}>{currentBreakpoint}</span>
	</div>
{/if}
